trigger:
  - main  # O "master", según tu rama principal

pool:
  vmImage: 'ubuntu-latest'

variables:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=--enable-native-access=ALL-UNNAMED"

steps:
  # 1. Usa Java 11
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk
        echo "##vso[task.setvariable variable=JAVA_HOME]/usr/lib/jvm/java-11-openjdk-amd64"
        java -version

  # 2. Ejecuta Gradle: clean, test y genera el reporte
  - task: Gradle@2
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'clean test aggregate'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'

  # 3. Publica el reporte de Serenity como artefacto
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'target/site/serenity'
      artifactName: 'SerenityReport'
      publishLocation: 'Container'
